version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: ticketsbackend
    build:
      context: ./src
      dockerfile: Dockerfile
    hostname: src
    restart: always
    logging: *default-logging

  web:
    build:
      context: ./nginx2
      dockerfile: Dockerfile

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
      - "80:80"
      - "5443:5443"

    depends_on:
      - api
      - web
    restart: always
    volumes:
      - /etc/letsencrypt/live/ticket.northeurope.cloudapp.azure.com/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/ticket.northeurope.cloudapp.azure.com/privkey.pem:/etc/nginx/privkey.pem
    logging: *default-logging
    

 
