version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file

services:
  api:
    image: ticketsbackend
    build:
      context: ./src
      dockerfile: Dockerfile
    hostname: src
    restart: always
    logging: *default-logging

  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "4443:443"
      - "80:80"
    depends_on:
      - api
    restart: always
    volumes:
      - ./nginx/cert.pem:/etc/nginx/cert.pem
      - ./nginx/cert.key:/etc/nginx/cert.key
    logging: *default-logging
    

 
